version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: server
    image: server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  gateway:
    build: gateway
    image: gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090