version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: server
    image: server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_SERVER=db
      - DB_PORT=5432
      - DB_NAME=shareit
      - PG_USER=root
      - PG_PASSWORD=root

  gateway:
    build: gateway
    image: gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_ADDRESS=server
      - SHAREIT_SERVER_PORT=9090